### ISSUE TITLE
Font Preview On Hover | Font Stack

### ISSUE THREAD

**Issue by Mesure73L** [BeepBot99/website-design-system#1]
first issue btw

On hover on font:
  get the font
  set the lorem ipsum font
    - to be the font that the user is hovering over

For example:
  if i hover over roboto mono
    - it shows the lorem ipsum text above to be roboto mono
 
> ok a few problems
> some fonts are not on google fonts
> like segoe ui
> and apple's default font
> (which is nameless)
> because they're only for one os

then use some other library that has it
or
dont change it if the font isnt available

the reason i want this is so that you can see what it would look like on other browsers or devices, so if you dont want a specific font to show or something you can easily remove it from the font stack

**Comment by BeepBot99** [comment]
Suggestion pending.
I am too lazy to do this, but if you can get it up and running, then I will accept it.
It would be a nice feature, but it is not essential.
I am not pointing anything out, but please use proper grammar here.
Do you need help with editing this code and creating a pull request or do you know how to do it?

**Comment by Mesure73L** [comment]
> Suggestion pending. I am too lazy to do this, but if you can get it up and running, then I will accept it. It would be a nice feature, but it is not essential. I am not pointing anything out, but please use proper grammar here. Do you need help with editing this code and creating a pull request or do you know how to do it?

You pointed it out. Also, the reason it isn't proper grammar is because I took it from our messages on Discord.
While it isn't essential, it would be a good quality of life improvement. I will maybe possibly try sometime eventually to figure it out.

**Comment by BeepBot99** [comment]
Ok. This issue is now closed.
